name: Scheduled Batch Processing

on:
  schedule:
    # Runs the workflow every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch:  # This enables manual triggering

jobs:
  batch_processing_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Script
      run: |
        python spma.py  # This runs your Python script which should save files like model/stock_price_model.h5

    - name: Commit and Push changes
      run: |
        git config --global user.name "Pranav singh"
        git config --global user.email "pranavsingh2811@gmail.com"
        git add .
        git commit -m "Add generated files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
