name: Schedule Data Processing

on:
  schedule:
    - cron: '0 * * * *'  # This runs every hour

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Data Processing Notebook
      run: |
        jupyter nbconvert --to notebook --execute --inplace spma.py

