name: Scheduled Batch Processing

on:
  schedule:
    # Runs the workflow every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch:  # This enables manual triggering

jobs:
  batch_processing_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gdown  # If you're using gdown in your script, ensure it's installed

    - name: Run Python Script
      run: |
        python spma.py  # This runs your Python script which handles the downloading and processing
